# Generated by Django 3.2.8 on 2021-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='description',
        ),
        migrations.AlterField(
            model_name='give',
            name='category',
            field=models.CharField(blank=True, choices=[('furniture', 'Furniture'), ('clothe', 'Clothes'), ('shoe', 'Shoes'), ('toy', 'toys'), ('electronics', 'Electronics'), ('bags', 'Bags'), ('mobile', 'mobile-phones'), ('laptop', 'Laptops'), ('book', 'Books'), ('kitchen-utensils', 'Kitchen-utensils'), ('bicycle', 'Bicyle'), ('accessories', 'Accessories'), ('food-stuffs', 'Food-stuffs'), ('groceries', 'Groceries'), ('generator', 'Generator'), ('beauty-product', 'Beauty-product'), ('others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('clothe', 'Clothes'), ('shoe', 'Shoes'), ('toy', 'toys'), ('electronics', 'Electronics'), ('bags', 'Bags'), ('mobile', 'mobile-phones'), ('laptop', 'Laptops'), ('book', 'Books'), ('kitchen-utensils', 'Kitchen-utensils'), ('bicycle', 'Bicyle'), ('accessories', 'Accessories'), ('food-stuffs', 'Food-stuffs'), ('groceries', 'Groceries'), ('generator', 'Generator'), ('beauty-product', 'Beauty-product'), ('others', 'Others')], max_length=100),
        ),
    ]
