# Generated by Django 3.2.8 on 2021-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0006_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('comment', models.TextField()),
                ('replied_on', models.DateTimeField(auto_now_add=True)),
                ('replied_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
