# Generated by Django 3.2.8 on 2021-12-05 21:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0007_auto_20211125_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, size=[250, 250], upload_to=''),
        ),
    ]
