# Generated by Django 3.2.8 on 2021-12-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0008_alter_give_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='give',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='description',
        ),
    ]
