# Generated by Django 3.2.8 on 2022-01-08 08:38

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0009_auto_20211217_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDeliveryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.CharField(blank=True, max_length=50, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('pickup_location', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=500, null=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='give',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, size=[500, 500], upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('on-delivery', 'on-delivery')], default='unpaid', max_length=30),
        ),
    ]
