# Generated by Django 3.2.8 on 2022-07-30 13:30

from django.db import migrations, models
import givers.models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0016_auto_20220522_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(validators=[givers.models.validate_number])),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('clothe', 'Clothes'), ('shoe', 'Shoes'), ('toy', 'toys'), ('electronics', 'Electronics'), ('bags', 'Bags'), ('mobile', 'mobile-phones'), ('laptop', 'Laptops'), ('book', 'Books'), ('kitchen-utensils', 'Kitchen-utensils'), ('bicycle', 'Bicyle'), ('accessories', 'Accessories'), ('food-stuffs', 'Food-stuffs'), ('groceries', 'Groceries'), ('generator', 'Generator'), ('beauty-product', 'Beauty-product'), ('others', 'Others')], max_length=50)),
                ('nature', models.CharField(blank=True, choices=[('single-items', 'single-items'), ('box', 'box/bag')], max_length=50)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('offered_on', models.DateField(auto_now_add=True)),
                ('address', models.TextField()),
                ('activate', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
            ],
        ),
    ]
