# Generated by Django 3.2.8 on 2022-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0017_giveaway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='address',
            field=models.TextField(default='Head office'),
        ),
    ]
