# Generated by Django 3.2.8 on 2022-12-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0018_alter_give_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='address',
        ),
        migrations.RemoveField(
            model_name='give',
            name='giver_number',
        ),
        migrations.RemoveField(
            model_name='give',
            name='user',
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='nature',
            field=models.CharField(blank=True, choices=[('single-items', 'single-items'), ('box', 'boxes/bags')], max_length=50),
        ),
    ]
