# Generated by Django 3.2.8 on 2023-02-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0019_auto_20221214_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveawayCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopper', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in-cart', 'in-cart'), ('ordered', 'ordered')], default='in-cart', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ondeliverytransaction',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='give',
            name='details',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='give',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('O', 'Others')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='give',
            name='product_class',
            field=models.CharField(choices=[('standard', 'standard'), ('premium', 'premium')], default='standard', max_length=15),
        ),
        migrations.AddField(
            model_name='give',
            name='tag_name',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='ondeliverytransaction',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='ondeliverytransaction',
            name='items',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='give',
            name='category',
            field=models.CharField(blank=True, choices=[('furniture', 'Furniture'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('toys', 'toys'), ('electronics', 'Electronics'), ('bag', 'Bags'), ('mobile', 'mobile-phones'), ('laptop', 'Laptops'), ('book', 'Books'), ('kitchen', 'Kitchen-utensils'), ('bicycle', 'Bicyle'), ('accessories', 'Accessories'), ('food', 'Food-stuffs'), ('groceries', 'Groceries'), ('generator', 'Generator'), ('beauty', 'Beauty-product'), ('natives', 'Natives'), ('corporate', 'Corporate')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='give',
            name='gift_status',
            field=models.CharField(blank=True, choices=[('unpicked', 'unpicked'), ('requested', 'requested'), ('ordered', 'ordered')], default='unpicked', max_length=30),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('toys', 'toys'), ('electronics', 'Electronics'), ('bag', 'Bags'), ('mobile', 'mobile-phones'), ('laptop', 'Laptops'), ('book', 'Books'), ('kitchen', 'Kitchen-utensils'), ('bicycle', 'Bicyle'), ('accessories', 'Accessories'), ('food', 'Food-stuffs'), ('groceries', 'Groceries'), ('generator', 'Generator'), ('beauty', 'Beauty-product'), ('natives', 'Natives'), ('corporate', 'Corporate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('O', 'Others')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='givers.give'),
        ),
    ]
